name: docker 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  
    - name: docker push into ecr
      run: |
        aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 487303169522.dkr.ecr.us-west-1.amazonaws.com
        docker build -t basha .
        docker tag basha:latest 487303169522.dkr.ecr.us-west-1.amazonaws.com/basha:latest
        docker push 487303169522.dkr.ecr.us-west-1.amazonaws.com/basha:latest
  
